# Generated by Django 2.2.1 on 2019-06-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190617_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0712345678', max_length=13),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
