# Generated by Django 2.2.1 on 2019-06-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], default='Nairobi', max_length=300)),
                ('period', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sublocation', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], max_length=300)),
                ('unitofsale', models.CharField(choices=[('whole', 'whole unit'), ('item', 'per single item')], max_length=10)),
                ('image', models.FileField(blank=True, upload_to='products_images/')),
                ('sublocation', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sell.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], default='Nairobi', max_length=150)),
                ('description', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='other', max_length=50)),
                ('period', models.DateTimeField()),
                ('sublocation', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sell.Category')),
                ('user', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Growing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], default='Nairobi', max_length=300)),
                ('image', models.FileField(blank=True, upload_to='products_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unitofsale', models.CharField(choices=[('whole', 'whole unit'), ('item', 'per single item')], max_length=10)),
                ('sublocation', models.CharField(default='Njoro', max_length=100)),
                ('MaturityDate', models.DateTimeField()),
                ('DescribeFarming', models.TextField(max_length=450)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growingProducts', to='sell.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
