# Generated by Django 2.2.1 on 2019-06-11 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], default='Nairobi', max_length=300)),
                ('period', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('equipment', 'FARM EQUIPMENT'), ('cereals', 'CEREALS'), ('vegetables', 'VEGETABLES'), ('livestock', 'LIVESTOCK'), ('other', 'OTHER'), ('cash crops', 'CASH CROPS'), ('agrochemicals', 'AGROCHEMICALS'), ('fruits', 'FRUITS'), (' fertilizers', 'FERTILIZERS'), ('fishery', 'FISHERY')], default='other', max_length=10)),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], default='Nairobi', max_length=150)),
                ('description', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='other', max_length=50)),
                ('period', models.CharField(default='week', max_length=100)),
                ('user', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elegeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Isiolo', 'ISIOLO'), ('Homa Bay', 'HOMA BAY'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Bungoma', 'BUNGOMA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('mandera', 'MANDERA'), ('meru', 'MERU'), ('migori', 'MIGORI'), ('marsabit', 'MARSABIT'), ('mombasa', 'MOMBASA'), ('muranga', 'MURANGA'), ('nairobi', 'NAIROBI'), ('nakuru', 'NAKURU'), ('nandi', 'NANDI'), ('narok', 'NAROK'), ('nyamira', 'NYAMIRA'), ('nyandarua', 'NYANDARUA'), ('nyeri', 'NYERI'), ('samburu', 'SAMBURU'), ('siaya', 'SIAYA'), ('taita taveta', 'TAITA TAVETA'), ('tana river', 'TANA RIVER'), ('tharaka nithi', 'THARAKA NITHI'), ('trans nzoia', 'TRANS NZOIA'), ('turkana', 'TURKANA'), ('uasin gishu', 'UASIN GISHU'), ('vihiga', 'VIHIGA'), ('wajir', 'WAJIR'), ('west pokot', 'WEST POKOT')], default='Nairobi', max_length=300)),
                ('category', models.CharField(choices=[('equipment', 'FARM EQUIPMENT'), ('cereals', 'CEREALS'), ('vegetables', 'VEGETABLES'), ('livestock', 'LIVESTOCK'), ('other', 'OTHER'), ('cash crops', 'CASH CROPS'), ('agrochemicals', 'AGROCHEMICALS'), ('fruits', 'FRUITS'), (' fertilizers', 'FERTILIZERS'), ('fishery', 'FISHERY')], default='other', max_length=10)),
                ('unitofsale', models.CharField(choices=[('whole', 'whole unit'), ('item', 'per single item')], max_length=10)),
                ('image', models.FileField(blank=True, upload_to='products_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200)),
                ('user', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
