# Generated by Django 2.2.1 on 2019-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20190614_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='period',
            field=models.DateTimeField(),
        ),
    ]
