# Generated by Django 2.2.1 on 2019-06-21 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_auto_20190621_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
